def tool_get_weather(location: str) -> dict:
    """
    Get the current weather using the Serper API.

    Returns:
        dict: JSON response from the API, or None if an error occurred
    """
    return {
        "forecastDays":[
            {
                "interval":{
                    "startTime":"2025-07-31T14:00:00Z",
                    "endTime":"2025-08-01T14:00:00Z"
                },
                "displayDate":{
                    "year":2025,
                    "month":7,
                    "day":31
                },
                "daytimeForecast":{
                    "interval":{
                        "startTime":"2025-07-31T14:00:00Z",
                        "endTime":"2025-08-01T02:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/sunny",
                        "description":{
                            "text":"Sunny",
                            "languageCode":"en"
                        },
                        "type":"CLEAR"
                    },
                    "relativeHumidity":65,
                    "uvIndex":10,
                    "precipitation":{
                        "probability":{
                            "percent":10,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":287,
                            "cardinal":"WEST_NORTHWEST"
                        },
                        "speed":{
                            "value":11,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":26,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":72,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "nighttimeForecast":{
                    "interval":{
                        "startTime":"2025-08-01T02:00:00Z",
                        "endTime":"2025-08-01T14:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/partly_clear",
                        "description":{
                            "text":"Partly cloudy",
                            "languageCode":"en"
                        },
                        "type":"PARTLY_CLOUDY"
                    },
                    "relativeHumidity":86,
                    "uvIndex":0,
                    "precipitation":{
                        "probability":{
                            "percent":5,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":267,
                            "cardinal":"WEST"
                        },
                        "speed":{
                            "value":8,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":19,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":57,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "maxTemperature":{
                    "degrees":24.7,
                    "unit":"CELSIUS"
                },
                "minTemperature":{
                    "degrees":15.4,
                    "unit":"CELSIUS"
                },
                "feelsLikeMaxTemperature":{
                    "degrees":25.8,
                    "unit":"CELSIUS"
                },
                "feelsLikeMinTemperature":{
                    "degrees":15.4,
                    "unit":"CELSIUS"
                },
                "sunEvents":{
                    "sunriseTime":"2025-07-31T13:12:11.131176683Z",
                    "sunsetTime":"2025-08-01T03:16:44.206149831Z"
                },
                "moonEvents":{
                    "moonPhase":"FIRST_QUARTER",
                    "moonriseTimes":[
                        "2025-07-31T20:09:21.921910747Z"
                    ],
                    "moonsetTimes":[
                        "2025-08-01T06:44:17.983999642Z"
                    ]
                },
                "maxHeatIndex":{
                    "degrees":25.8,
                    "unit":"CELSIUS"
                }
            },
            {
                "interval":{
                    "startTime":"2025-08-01T14:00:00Z",
                    "endTime":"2025-08-02T14:00:00Z"
                },
                "displayDate":{
                    "year":2025,
                    "month":8,
                    "day":1
                },
                "daytimeForecast":{
                    "interval":{
                        "startTime":"2025-08-01T14:00:00Z",
                        "endTime":"2025-08-02T02:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/sunny",
                        "description":{
                            "text":"Sunny",
                            "languageCode":"en"
                        },
                        "type":"CLEAR"
                    },
                    "relativeHumidity":69,
                    "uvIndex":10,
                    "precipitation":{
                        "probability":{
                            "percent":5,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":277,
                            "cardinal":"WEST"
                        },
                        "speed":{
                            "value":13,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":27,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":52,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "nighttimeForecast":{
                    "interval":{
                        "startTime":"2025-08-02T02:00:00Z",
                        "endTime":"2025-08-02T14:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/mostly_clear",
                        "description":{
                            "text":"Clear with periodic clouds",
                            "languageCode":"en"
                        },
                        "type":"MOSTLY_CLEAR"
                    },
                    "relativeHumidity":87,
                    "uvIndex":0,
                    "precipitation":{
                        "probability":{
                            "percent":15,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":10,
                    "wind":{
                        "direction":{
                            "degrees":238,
                            "cardinal":"WEST_SOUTHWEST"
                        },
                        "speed":{
                            "value":8,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":18,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":41,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "maxTemperature":{
                    "degrees":22.7,
                    "unit":"CELSIUS"
                },
                "minTemperature":{
                    "degrees":15,
                    "unit":"CELSIUS"
                },
                "feelsLikeMaxTemperature":{
                    "degrees":24.8,
                    "unit":"CELSIUS"
                },
                "feelsLikeMinTemperature":{
                    "degrees":15,
                    "unit":"CELSIUS"
                },
                "sunEvents":{
                    "sunriseTime":"2025-08-01T13:13:00.971926585Z",
                    "sunsetTime":"2025-08-02T03:15:46.194238262Z"
                },
                "moonEvents":{
                    "moonPhase":"FIRST_QUARTER",
                    "moonriseTimes":[
                        "2025-08-01T21:09:40.532883033Z"
                    ]
                },
                "maxHeatIndex":{
                    "degrees":24.8,
                    "unit":"CELSIUS"
                }
            },
            {
                "interval":{
                    "startTime":"2025-08-02T14:00:00Z",
                    "endTime":"2025-08-03T14:00:00Z"
                },
                "displayDate":{
                    "year":2025,
                    "month":8,
                    "day":2
                },
                "daytimeForecast":{
                    "interval":{
                        "startTime":"2025-08-02T14:00:00Z",
                        "endTime":"2025-08-03T02:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/sunny",
                        "description":{
                            "text":"Sunny",
                            "languageCode":"en"
                        },
                        "type":"CLEAR"
                    },
                    "relativeHumidity":71,
                    "uvIndex":10,
                    "precipitation":{
                        "probability":{
                            "percent":15,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":10,
                    "wind":{
                        "direction":{
                            "degrees":280,
                            "cardinal":"WEST"
                        },
                        "speed":{
                            "value":11,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":24,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":44,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "nighttimeForecast":{
                    "interval":{
                        "startTime":"2025-08-03T02:00:00Z",
                        "endTime":"2025-08-03T14:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/partly_clear",
                        "description":{
                            "text":"Partly cloudy",
                            "languageCode":"en"
                        },
                        "type":"PARTLY_CLOUDY"
                    },
                    "relativeHumidity":86,
                    "uvIndex":0,
                    "precipitation":{
                        "probability":{
                            "percent":0,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":234,
                            "cardinal":"SOUTHWEST"
                        },
                        "speed":{
                            "value":8,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":18,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":37,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "maxTemperature":{
                    "degrees":22.6,
                    "unit":"CELSIUS"
                },
                "minTemperature":{
                    "degrees":14.9,
                    "unit":"CELSIUS"
                },
                "feelsLikeMaxTemperature":{
                    "degrees":24.8,
                    "unit":"CELSIUS"
                },
                "feelsLikeMinTemperature":{
                    "degrees":14.9,
                    "unit":"CELSIUS"
                },
                "sunEvents":{
                    "sunriseTime":"2025-08-02T13:13:51.013769344Z",
                    "sunsetTime":"2025-08-03T03:14:46.784208421Z"
                },
                "moonEvents":{
                    "moonPhase":"WAXING_GIBBOUS",
                    "moonriseTimes":[
                        "2025-08-02T22:10:51.378213368Z"
                    ],
                    "moonsetTimes":[
                        "2025-08-02T07:12:31.103821357Z"
                    ]
                },
                "maxHeatIndex":{
                    "degrees":24.8,
                    "unit":"CELSIUS"
                }
            },
            {
                "interval":{
                    "startTime":"2025-08-03T14:00:00Z",
                    "endTime":"2025-08-04T14:00:00Z"
                },
                "displayDate":{
                    "year":2025,
                    "month":8,
                    "day":3
                },
                "daytimeForecast":{
                    "interval":{
                        "startTime":"2025-08-03T14:00:00Z",
                        "endTime":"2025-08-04T02:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/sunny",
                        "description":{
                            "text":"Sunny",
                            "languageCode":"en"
                        },
                        "type":"CLEAR"
                    },
                    "relativeHumidity":67,
                    "uvIndex":10,
                    "precipitation":{
                        "probability":{
                            "percent":0,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":270,
                            "cardinal":"WEST"
                        },
                        "speed":{
                            "value":13,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":27,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":32,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "nighttimeForecast":{
                    "interval":{
                        "startTime":"2025-08-04T02:00:00Z",
                        "endTime":"2025-08-04T14:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/clear",
                        "description":{
                            "text":"Clear",
                            "languageCode":"en"
                        },
                        "type":"CLEAR"
                    },
                    "relativeHumidity":80,
                    "uvIndex":0,
                    "precipitation":{
                        "probability":{
                            "percent":0,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":231,
                            "cardinal":"SOUTHWEST"
                        },
                        "speed":{
                            "value":10,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":19,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":10,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "maxTemperature":{
                    "degrees":21.6,
                    "unit":"CELSIUS"
                },
                "minTemperature":{
                    "degrees":14.4,
                    "unit":"CELSIUS"
                },
                "feelsLikeMaxTemperature":{
                    "degrees":24.9,
                    "unit":"CELSIUS"
                },
                "feelsLikeMinTemperature":{
                    "degrees":14,
                    "unit":"CELSIUS"
                },
                "sunEvents":{
                    "sunriseTime":"2025-08-03T13:14:41.233147486Z",
                    "sunsetTime":"2025-08-04T03:13:46.002892014Z"
                },
                "moonEvents":{
                    "moonPhase":"WAXING_GIBBOUS",
                    "moonriseTimes":[
                        "2025-08-03T23:11:57.238380754Z"
                    ],
                    "moonsetTimes":[
                        "2025-08-03T07:45:56.264785477Z"
                    ]
                },
                "maxHeatIndex":{
                    "degrees":24.9,
                    "unit":"CELSIUS"
                }
            },
            {
                "interval":{
                    "startTime":"2025-08-04T14:00:00Z",
                    "endTime":"2025-08-05T14:00:00Z"
                },
                "displayDate":{
                    "year":2025,
                    "month":8,
                    "day":4
                },
                "daytimeForecast":{
                    "interval":{
                        "startTime":"2025-08-04T14:00:00Z",
                        "endTime":"2025-08-05T02:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/sunny",
                        "description":{
                            "text":"Sunny",
                            "languageCode":"en"
                        },
                        "type":"CLEAR"
                    },
                    "relativeHumidity":63,
                    "uvIndex":10,
                    "precipitation":{
                        "probability":{
                            "percent":0,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":270,
                            "cardinal":"WEST"
                        },
                        "speed":{
                            "value":13,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":27,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":14,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "nighttimeForecast":{
                    "interval":{
                        "startTime":"2025-08-05T02:00:00Z",
                        "endTime":"2025-08-05T14:00:00Z"
                    },
                    "weatherCondition":{
                        "iconBaseUri":"https://maps.gstatic.com/weather/v1/clear",
                        "description":{
                            "text":"Clear",
                            "languageCode":"en"
                        },
                        "type":"CLEAR"
                    },
                    "relativeHumidity":83,
                    "uvIndex":0,
                    "precipitation":{
                        "probability":{
                            "percent":0,
                            "type":"RAIN"
                        },
                        "snowQpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        },
                        "qpf":{
                            "quantity":0,
                            "unit":"MILLIMETERS"
                        }
                    },
                    "thunderstormProbability":0,
                    "wind":{
                        "direction":{
                            "degrees":234,
                            "cardinal":"SOUTHWEST"
                        },
                        "speed":{
                            "value":10,
                            "unit":"KILOMETERS_PER_HOUR"
                        },
                        "gust":{
                            "value":19,
                            "unit":"KILOMETERS_PER_HOUR"
                        }
                    },
                    "cloudCover":36,
                    "iceThickness":{
                        "thickness":0,
                        "unit":"MILLIMETERS"
                    }
                },
                "maxTemperature":{
                    "degrees":21.8,
                    "unit":"CELSIUS"
                },
                "minTemperature":{
                    "degrees":13.7,
                    "unit":"CELSIUS"
                },
                "feelsLikeMaxTemperature":{
                    "degrees":24.5,
                    "unit":"CELSIUS"
                },
                "feelsLikeMinTemperature":{
                    "degrees":13.7,
                    "unit":"CELSIUS"
                },
                "sunEvents":{
                    "sunriseTime":"2025-08-04T13:15:31.607592606Z",
                    "sunsetTime":"2025-08-05T03:12:43.877509027Z"
                },
                "moonEvents":{
                    "moonPhase":"WAXING_GIBBOUS",
                    "moonriseTimes":[
                        "2025-08-05T00:10:59.589992285Z"
                    ],
                    "moonsetTimes":[
                        "2025-08-04T08:26:17.839900090Z"
                    ]
                },
                "maxHeatIndex":{
                    "degrees":24.5,
                    "unit":"CELSIUS"
                }
            }
        ],
        "timeZone":{
            "id":"America/Los_Angeles"
        },
        "nextPageToken":"ChgKEgm8dJMYBLZCQBH-ZffkYYVewBAHGAIQBRgFIgwItPSyxAYQx8XM9wEqE0FtZXJpY2EvTG9zX0FuZ2VsZXM="
    }
